-- =============================================
-- SEED DE CATEGORÍAS Y PERSONAJES
-- Ejecutar en la base de datos 'personajes'
-- =============================================

-- Limpiar tablas existentes (opcional)
-- DELETE FROM characters;
-- DELETE FROM categories;

-- =============================================
-- CATEGORÍAS
-- =============================================

INSERT INTO categories (name, description, icon, isActive, createdAt, updatedAt) VALUES
('Harry Potter', 'Personajes del mundo mágico de Harry Potter', '⚡', 1, NOW(), NOW()),
('Disney Clásico', 'Personajes clásicos de películas Disney', '🏰', 1, NOW(), NOW()),
('Disney Pixar', 'Personajes de películas Pixar', '🎬', 1, NOW(), NOW()),
('Marvel', 'Superhéroes y villanos del universo Marvel', '🦸', 1, NOW(), NOW()),
('DC Comics', 'Superhéroes y villanos de DC', '🦇', 1, NOW(), NOW()),
('Anime Shonen', 'Personajes de anime shonen popular', '⚔️', 1, NOW(), NOW()),
('Anime Clásico', 'Personajes de anime clásico', '🎌', 1, NOW(), NOW()),
('Studio Ghibli', 'Personajes de películas de Ghibli', '🌿', 1, NOW(), NOW()),
('Juego de Tronos', 'Personajes de Game of Thrones', '🐉', 1, NOW(), NOW()),
('Breaking Bad', 'Personajes de Breaking Bad y Better Call Saul', '🧪', 1, NOW(), NOW()),
('The Office', 'Personajes de The Office US', '📎', 1, NOW(), NOW()),
('Friends', 'Personajes de la serie Friends', '☕', 1, NOW(), NOW()),
('Stranger Things', 'Personajes de Stranger Things', '🔦', 1, NOW(), NOW()),
('La Casa de Papel', 'Personajes de La Casa de Papel', '💰', 1, NOW(), NOW()),
('Los Simpson', 'Personajes de Los Simpson', '🍩', 1, NOW(), NOW()),
('Bob Esponja', 'Personajes de Bob Esponja', '🧽', 1, NOW(), NOW()),
('Star Wars', 'Personajes del universo Star Wars', '⭐', 1, NOW(), NOW()),
('El Señor de los Anillos', 'Personajes de LOTR y El Hobbit', '💍', 1, NOW(), NOW()),
('Cantantes Pop', 'Artistas de música pop internacional', '🎤', 1, NOW(), NOW()),
('Cantantes Reggaeton', 'Artistas de reggaeton y urbano', '🎧', 1, NOW(), NOW()),
('Cantantes Rock', 'Artistas y bandas de rock', '🎸', 1, NOW(), NOW()),
('Futbolistas', 'Jugadores de fútbol famosos', '⚽', 1, NOW(), NOW()),
('NBA', 'Jugadores de baloncesto de la NBA', '🏀', 1, NOW(), NOW()),
('Videojuegos Nintendo', 'Personajes de juegos Nintendo', '🍄', 1, NOW(), NOW()),
('Videojuegos PlayStation', 'Personajes de exclusivos PlayStation', '🎮', 1, NOW(), NOW()),
('Pokémon', 'Pokémon y entrenadores', '⚡', 1, NOW(), NOW()),
('Nickelodeon', 'Personajes de series Nickelodeon', '🟠', 1, NOW(), NOW()),
('Cartoon Network', 'Personajes de Cartoon Network', '🟣', 1, NOW(), NOW()),
('Shrek y DreamWorks', 'Personajes de películas DreamWorks', '🧅', 1, NOW(), NOW()),
('Películas de Terror', 'Villanos y personajes de terror', '👻', 1, NOW(), NOW()),
('Películas de Acción', 'Héroes de películas de acción', '💥', 1, NOW(), NOW()),
('Comedia Romántica', 'Personajes de comedias románticas', '💕', 1, NOW(), NOW()),
('Youtubers', 'Creadores de contenido famosos', '▶️', 1, NOW(), NOW()),
('Personajes Históricos', 'Figuras importantes de la historia', '📜', 1, NOW(), NOW()),
('Mitología Griega', 'Dioses y héroes de la mitología', '⚡', 1, NOW(), NOW());

-- =============================================
-- PERSONAJES POR CATEGORÍA
-- =============================================

-- Harry Potter (ID: 1)
INSERT INTO characters (name, categoryId, createdAt, updatedAt) VALUES
('Harry Potter', 1, NOW(), NOW()),
('Hermione Granger', 1, NOW(), NOW()),
('Ron Weasley', 1, NOW(), NOW()),
('Albus Dumbledore', 1, NOW(), NOW()),
('Lord Voldemort', 1, NOW(), NOW()),
('Severus Snape', 1, NOW(), NOW()),
('Draco Malfoy', 1, NOW(), NOW()),
('Rubeus Hagrid', 1, NOW(), NOW()),
('Sirius Black', 1, NOW(), NOW()),
('Dobby', 1, NOW(), NOW()),
('Bellatrix Lestrange', 1, NOW(), NOW()),
('Neville Longbottom', 1, NOW(), NOW()),
('Luna Lovegood', 1, NOW(), NOW()),
('Ginny Weasley', 1, NOW(), NOW()),
('Fred Weasley', 1, NOW(), NOW()),
('George Weasley', 1, NOW(), NOW()),
('Minerva McGonagall', 1, NOW(), NOW()),
('Remus Lupin', 1, NOW(), NOW()),
('Alastor Moody', 1, NOW(), NOW()),
('Nymphadora Tonks', 1, NOW(), NOW()),
('Cedric Diggory', 1, NOW(), NOW()),
('Cho Chang', 1, NOW(), NOW()),
('Lucius Malfoy', 1, NOW(), NOW()),
('Molly Weasley', 1, NOW(), NOW()),
('Arthur Weasley', 1, NOW(), NOW()),
('Dolores Umbridge', 1, NOW(), NOW()),
('Gilderoy Lockhart', 1, NOW(), NOW()),
('Horace Slughorn', 1, NOW(), NOW()),
('Newt Scamander', 1, NOW(), NOW()),
('Gellert Grindelwald', 1, NOW(), NOW());

-- Disney Clásico (ID: 2)
INSERT INTO characters (name, categoryId, createdAt, updatedAt) VALUES
('Mickey Mouse', 2, NOW(), NOW()),
('Minnie Mouse', 2, NOW(), NOW()),
('Donald Duck', 2, NOW(), NOW()),
('Goofy', 2, NOW(), NOW()),
('Pluto', 2, NOW(), NOW()),
('Blancanieves', 2, NOW(), NOW()),
('Cenicienta', 2, NOW(), NOW()),
('Aurora (Bella Durmiente)', 2, NOW(), NOW()),
('Ariel', 2, NOW(), NOW()),
('Bella', 2, NOW(), NOW()),
('Bestia', 2, NOW(), NOW()),
('Jasmine', 2, NOW(), NOW()),
('Aladdín', 2, NOW(), NOW()),
('Genio', 2, NOW(), NOW()),
('Mulán', 2, NOW(), NOW()),
('Pocahontas', 2, NOW(), NOW()),
('Rapunzel', 2, NOW(), NOW()),
('Flynn Rider', 2, NOW(), NOW()),
('Elsa', 2, NOW(), NOW()),
('Anna', 2, NOW(), NOW()),
('Olaf', 2, NOW(), NOW()),
('Moana', 2, NOW(), NOW()),
('Maui', 2, NOW(), NOW()),
('Simba', 2, NOW(), NOW()),
('Mufasa', 2, NOW(), NOW()),
('Scar', 2, NOW(), NOW()),
('Timón', 2, NOW(), NOW()),
('Pumba', 2, NOW(), NOW()),
('Stitch', 2, NOW(), NOW()),
('Maléfica', 2, NOW(), NOW());

-- Disney Pixar (ID: 3)
INSERT INTO characters (name, categoryId, createdAt, updatedAt) VALUES
('Woody', 3, NOW(), NOW()),
('Buzz Lightyear', 3, NOW(), NOW()),
('Jessie', 3, NOW(), NOW()),
('Rex', 3, NOW(), NOW()),
('Mr. Potato', 3, NOW(), NOW()),
('Nemo', 3, NOW(), NOW()),
('Dory', 3, NOW(), NOW()),
('Marlin', 3, NOW(), NOW()),
('Bob Parr (Mr. Increíble)', 3, NOW(), NOW()),
('Elastigirl', 3, NOW(), NOW()),
('Violeta Parr', 3, NOW(), NOW()),
('Dash Parr', 3, NOW(), NOW()),
('Jack-Jack', 3, NOW(), NOW()),
('Edna Moda', 3, NOW(), NOW()),
('Mike Wazowski', 3, NOW(), NOW()),
('Sulley', 3, NOW(), NOW()),
('Boo', 3, NOW(), NOW()),
('Rayo McQueen', 3, NOW(), NOW()),
('Mate', 3, NOW(), NOW()),
('WALL-E', 3, NOW(), NOW()),
('EVA', 3, NOW(), NOW()),
('Carl Fredricksen', 3, NOW(), NOW()),
('Russell', 3, NOW(), NOW()),
('Dug', 3, NOW(), NOW()),
('Remy', 3, NOW(), NOW()),
('Alfredo Linguini', 3, NOW(), NOW()),
('Joy (Alegría)', 3, NOW(), NOW()),
('Sadness (Tristeza)', 3, NOW(), NOW()),
('Miguel Rivera', 3, NOW(), NOW()),
('Héctor', 3, NOW(), NOW());

-- Marvel (ID: 4)
INSERT INTO characters (name, categoryId, createdAt, updatedAt) VALUES
('Iron Man', 4, NOW(), NOW()),
('Capitán América', 4, NOW(), NOW()),
('Thor', 4, NOW(), NOW()),
('Hulk', 4, NOW(), NOW()),
('Black Widow', 4, NOW(), NOW()),
('Hawkeye', 4, NOW(), NOW()),
('Spider-Man', 4, NOW(), NOW()),
('Doctor Strange', 4, NOW(), NOW()),
('Black Panther', 4, NOW(), NOW()),
('Scarlet Witch', 4, NOW(), NOW()),
('Vision', 4, NOW(), NOW()),
('Ant-Man', 4, NOW(), NOW()),
('Wasp', 4, NOW(), NOW()),
('Captain Marvel', 4, NOW(), NOW()),
('Star-Lord', 4, NOW(), NOW()),
('Gamora', 4, NOW(), NOW()),
('Drax', 4, NOW(), NOW()),
('Rocket Raccoon', 4, NOW(), NOW()),
('Groot', 4, NOW(), NOW()),
('Nebula', 4, NOW(), NOW()),
('Thanos', 4, NOW(), NOW()),
('Loki', 4, NOW(), NOW()),
('Nick Fury', 4, NOW(), NOW()),
('Bucky Barnes', 4, NOW(), NOW()),
('Falcon', 4, NOW(), NOW()),
('War Machine', 4, NOW(), NOW()),
('Shang-Chi', 4, NOW(), NOW()),
('Deadpool', 4, NOW(), NOW()),
('Wolverine', 4, NOW(), NOW()),
('Professor X', 4, NOW(), NOW());

-- DC Comics (ID: 5)
INSERT INTO characters (name, categoryId, createdAt, updatedAt) VALUES
('Batman', 5, NOW(), NOW()),
('Superman', 5, NOW(), NOW()),
('Wonder Woman', 5, NOW(), NOW()),
('Aquaman', 5, NOW(), NOW()),
('The Flash', 5, NOW(), NOW()),
('Cyborg', 5, NOW(), NOW()),
('Green Lantern', 5, NOW(), NOW()),
('Shazam', 5, NOW(), NOW()),
('Joker', 5, NOW(), NOW()),
('Harley Quinn', 5, NOW(), NOW()),
('Catwoman', 5, NOW(), NOW()),
('Poison Ivy', 5, NOW(), NOW()),
('Bane', 5, NOW(), NOW()),
('Riddler', 5, NOW(), NOW()),
('Penguin', 5, NOW(), NOW()),
('Two-Face', 5, NOW(), NOW()),
('Alfred Pennyworth', 5, NOW(), NOW()),
('Robin', 5, NOW(), NOW()),
('Batgirl', 5, NOW(), NOW()),
('Nightwing', 5, NOW(), NOW()),
('Lex Luthor', 5, NOW(), NOW()),
('Darkseid', 5, NOW(), NOW()),
('Doomsday', 5, NOW(), NOW()),
('General Zod', 5, NOW(), NOW()),
('Black Adam', 5, NOW(), NOW()),
('Supergirl', 5, NOW(), NOW()),
('Martian Manhunter', 5, NOW(), NOW()),
('Green Arrow', 5, NOW(), NOW()),
('Black Canary', 5, NOW(), NOW()),
('Constantine', 5, NOW(), NOW());

-- Anime Shonen (ID: 6)
INSERT INTO characters (name, categoryId, createdAt, updatedAt) VALUES
('Goku', 6, NOW(), NOW()),
('Vegeta', 6, NOW(), NOW()),
('Gohan', 6, NOW(), NOW()),
('Piccolo', 6, NOW(), NOW()),
('Frieza', 6, NOW(), NOW()),
('Naruto Uzumaki', 6, NOW(), NOW()),
('Sasuke Uchiha', 6, NOW(), NOW()),
('Sakura Haruno', 6, NOW(), NOW()),
('Kakashi Hatake', 6, NOW(), NOW()),
('Itachi Uchiha', 6, NOW(), NOW()),
('Monkey D. Luffy', 6, NOW(), NOW()),
('Roronoa Zoro', 6, NOW(), NOW()),
('Sanji', 6, NOW(), NOW()),
('Nami', 6, NOW(), NOW()),
('Ichigo Kurosaki', 6, NOW(), NOW()),
('Rukia Kuchiki', 6, NOW(), NOW()),
('Eren Jaeger', 6, NOW(), NOW()),
('Mikasa Ackerman', 6, NOW(), NOW()),
('Levi Ackerman', 6, NOW(), NOW()),
('Tanjiro Kamado', 6, NOW(), NOW()),
('Nezuko Kamado', 6, NOW(), NOW()),
('Zenitsu Agatsuma', 6, NOW(), NOW()),
('Izuku Midoriya (Deku)', 6, NOW(), NOW()),
('All Might', 6, NOW(), NOW()),
('Bakugo Katsuki', 6, NOW(), NOW()),
('Gon Freecss', 6, NOW(), NOW()),
('Killua Zoldyck', 6, NOW(), NOW()),
('Saitama', 6, NOW(), NOW()),
('Genos', 6, NOW(), NOW()),
('Asta', 6, NOW(), NOW());

-- Anime Clásico (ID: 7)
INSERT INTO characters (name, categoryId, createdAt, updatedAt) VALUES
('Sailor Moon', 7, NOW(), NOW()),
('Tuxedo Mask', 7, NOW(), NOW()),
('Sakura Kinomoto', 7, NOW(), NOW()),
('Inuyasha', 7, NOW(), NOW()),
('Kagome Higurashi', 7, NOW(), NOW()),
('Edward Elric', 7, NOW(), NOW()),
('Alphonse Elric', 7, NOW(), NOW()),
('Light Yagami', 7, NOW(), NOW()),
('L', 7, NOW(), NOW()),
('Ryuk', 7, NOW(), NOW()),
('Spike Spiegel', 7, NOW(), NOW()),
('Faye Valentine', 7, NOW(), NOW()),
('Vash the Stampede', 7, NOW(), NOW()),
('Kenshin Himura', 7, NOW(), NOW()),
('Alucard', 7, NOW(), NOW()),
('Yusuke Urameshi', 7, NOW(), NOW()),
('Kurama', 7, NOW(), NOW()),
('Hiei', 7, NOW(), NOW()),
('Guts', 7, NOW(), NOW()),
('Griffith', 7, NOW(), NOW()),
('Lelouch Lamperouge', 7, NOW(), NOW()),
('C.C.', 7, NOW(), NOW()),
('Shinji Ikari', 7, NOW(), NOW()),
('Asuka Langley', 7, NOW(), NOW()),
('Rei Ayanami', 7, NOW(), NOW()),
('Motoko Kusanagi', 7, NOW(), NOW()),
('Astro Boy', 7, NOW(), NOW()),
('Doraemon', 7, NOW(), NOW()),
('Shin Chan', 7, NOW(), NOW()),
('Detective Conan', 7, NOW(), NOW());

-- Studio Ghibli (ID: 8)
INSERT INTO characters (name, categoryId, createdAt, updatedAt) VALUES
('Totoro', 8, NOW(), NOW()),
('Chihiro', 8, NOW(), NOW()),
('Haku', 8, NOW(), NOW()),
('Sin Cara (No-Face)', 8, NOW(), NOW()),
('Yubaba', 8, NOW(), NOW()),
('Sophie', 8, NOW(), NOW()),
('Howl', 8, NOW(), NOW()),
('Calcifer', 8, NOW(), NOW()),
('San (Princesa Mononoke)', 8, NOW(), NOW()),
('Ashitaka', 8, NOW(), NOW()),
('Kiki', 8, NOW(), NOW()),
('Jiji', 8, NOW(), NOW()),
('Ponyo', 8, NOW(), NOW()),
('Sosuke', 8, NOW(), NOW()),
('Sheeta', 8, NOW(), NOW()),
('Pazu', 8, NOW(), NOW()),
('Nausicaä', 8, NOW(), NOW()),
('Porco Rosso', 8, NOW(), NOW()),
('Arrietty', 8, NOW(), NOW()),
('Satsuki', 8, NOW(), NOW()),
('Mei', 8, NOW(), NOW()),
('Catbus', 8, NOW(), NOW()),
('Barón', 8, NOW(), NOW()),
('Muta', 8, NOW(), NOW());

-- Juego de Tronos (ID: 9)
INSERT INTO characters (name, categoryId, createdAt, updatedAt) VALUES
('Jon Snow', 9, NOW(), NOW()),
('Daenerys Targaryen', 9, NOW(), NOW()),
('Tyrion Lannister', 9, NOW(), NOW()),
('Cersei Lannister', 9, NOW(), NOW()),
('Jaime Lannister', 9, NOW(), NOW()),
('Arya Stark', 9, NOW(), NOW()),
('Sansa Stark', 9, NOW(), NOW()),
('Bran Stark', 9, NOW(), NOW()),
('Ned Stark', 9, NOW(), NOW()),
('Catelyn Stark', 9, NOW(), NOW()),
('Robb Stark', 9, NOW(), NOW()),
('The Hound (Sandor Clegane)', 9, NOW(), NOW()),
('The Mountain (Gregor Clegane)', 9, NOW(), NOW()),
('Joffrey Baratheon', 9, NOW(), NOW()),
('Robert Baratheon', 9, NOW(), NOW()),
('Stannis Baratheon', 9, NOW(), NOW()),
('Melisandre', 9, NOW(), NOW()),
('Davos Seaworth', 9, NOW(), NOW()),
('Varys', 9, NOW(), NOW()),
('Petyr Baelish (Littlefinger)', 9, NOW(), NOW()),
('Brienne of Tarth', 9, NOW(), NOW()),
('Samwell Tarly', 9, NOW(), NOW()),
('Jorah Mormont', 9, NOW(), NOW()),
('Grey Worm', 9, NOW(), NOW()),
('Missandei', 9, NOW(), NOW()),
('Theon Greyjoy', 9, NOW(), NOW()),
('Ramsay Bolton', 9, NOW(), NOW()),
('Night King', 9, NOW(), NOW()),
('Hodor', 9, NOW(), NOW()),
('Oberyn Martell', 9, NOW(), NOW());

-- Breaking Bad (ID: 10)
INSERT INTO characters (name, categoryId, createdAt, updatedAt) VALUES
('Walter White', 10, NOW(), NOW()),
('Jesse Pinkman', 10, NOW(), NOW()),
('Skyler White', 10, NOW(), NOW()),
('Hank Schrader', 10, NOW(), NOW()),
('Marie Schrader', 10, NOW(), NOW()),
('Walter White Jr.', 10, NOW(), NOW()),
('Saul Goodman', 10, NOW(), NOW()),
('Gus Fring', 10, NOW(), NOW()),
('Mike Ehrmantraut', 10, NOW(), NOW()),
('Tuco Salamanca', 10, NOW(), NOW()),
('Héctor Salamanca', 10, NOW(), NOW()),
('Los Primos (Salamanca Twins)', 10, NOW(), NOW()),
('Todd Alquist', 10, NOW(), NOW()),
('Lydia Rodarte-Quayle', 10, NOW(), NOW()),
('Jane Margolis', 10, NOW(), NOW()),
('Andrea Cantillo', 10, NOW(), NOW()),
('Badger', 10, NOW(), NOW()),
('Skinny Pete', 10, NOW(), NOW()),
('Kim Wexler', 10, NOW(), NOW()),
('Chuck McGill', 10, NOW(), NOW()),
('Howard Hamlin', 10, NOW(), NOW()),
('Nacho Varga', 10, NOW(), NOW()),
('Lalo Salamanca', 10, NOW(), NOW());

-- The Office (ID: 11)
INSERT INTO characters (name, categoryId, createdAt, updatedAt) VALUES
('Michael Scott', 11, NOW(), NOW()),
('Dwight Schrute', 11, NOW(), NOW()),
('Jim Halpert', 11, NOW(), NOW()),
('Pam Beesly', 11, NOW(), NOW()),
('Andy Bernard', 11, NOW(), NOW()),
('Kevin Malone', 11, NOW(), NOW()),
('Angela Martin', 11, NOW(), NOW()),
('Oscar Martinez', 11, NOW(), NOW()),
('Stanley Hudson', 11, NOW(), NOW()),
('Phyllis Vance', 11, NOW(), NOW()),
('Meredith Palmer', 11, NOW(), NOW()),
('Creed Bratton', 11, NOW(), NOW()),
('Ryan Howard', 11, NOW(), NOW()),
('Kelly Kapoor', 11, NOW(), NOW()),
('Toby Flenderson', 11, NOW(), NOW()),
('Darryl Philbin', 11, NOW(), NOW()),
('Erin Hannon', 11, NOW(), NOW()),
('Gabe Lewis', 11, NOW(), NOW()),
('Jan Levinson', 11, NOW(), NOW()),
('Holly Flax', 11, NOW(), NOW()),
('Robert California', 11, NOW(), NOW()),
('Nellie Bertram', 11, NOW(), NOW()),
('Pete Miller', 11, NOW(), NOW()),
('Clark Green', 11, NOW(), NOW());

-- Friends (ID: 12)
INSERT INTO characters (name, categoryId, createdAt, updatedAt) VALUES
('Rachel Green', 12, NOW(), NOW()),
('Monica Geller', 12, NOW(), NOW()),
('Phoebe Buffay', 12, NOW(), NOW()),
('Joey Tribbiani', 12, NOW(), NOW()),
('Chandler Bing', 12, NOW(), NOW()),
('Ross Geller', 12, NOW(), NOW()),
('Gunther', 12, NOW(), NOW()),
('Janice Litman', 12, NOW(), NOW()),
('Richard Burke', 12, NOW(), NOW()),
('Mike Hannigan', 12, NOW(), NOW()),
('Emily Waltham', 12, NOW(), NOW()),
('Carol Willick', 12, NOW(), NOW()),
('Susan Bunch', 12, NOW(), NOW()),
('Ben Geller', 12, NOW(), NOW()),
('Emma Geller-Green', 12, NOW(), NOW()),
('Jack Geller', 12, NOW(), NOW()),
('Judy Geller', 12, NOW(), NOW()),
('Ursula Buffay', 12, NOW(), NOW()),
('Frank Buffay Jr.', 12, NOW(), NOW()),
('Estelle Leonard', 12, NOW(), NOW());

-- Stranger Things (ID: 13)
INSERT INTO characters (name, categoryId, createdAt, updatedAt) VALUES
('Eleven', 13, NOW(), NOW()),
('Mike Wheeler', 13, NOW(), NOW()),
('Dustin Henderson', 13, NOW(), NOW()),
('Lucas Sinclair', 13, NOW(), NOW()),
('Will Byers', 13, NOW(), NOW()),
('Max Mayfield', 13, NOW(), NOW()),
('Steve Harrington', 13, NOW(), NOW()),
('Nancy Wheeler', 13, NOW(), NOW()),
('Jonathan Byers', 13, NOW(), NOW()),
('Joyce Byers', 13, NOW(), NOW()),
('Jim Hopper', 13, NOW(), NOW()),
('Eddie Munson', 13, NOW(), NOW()),
('Robin Buckley', 13, NOW(), NOW()),
('Erica Sinclair', 13, NOW(), NOW()),
('Murray Bauman', 13, NOW(), NOW()),
('Billy Hargrove', 13, NOW(), NOW()),
('Karen Wheeler', 13, NOW(), NOW()),
('Dr. Martin Brenner', 13, NOW(), NOW()),
('Demogorgon', 13, NOW(), NOW()),
('Mind Flayer', 13, NOW(), NOW()),
('Vecna', 13, NOW(), NOW()),
('Argyle', 13, NOW(), NOW()),
('Suzie Bingham', 13, NOW(), NOW());

-- La Casa de Papel (ID: 14)
INSERT INTO characters (name, categoryId, createdAt, updatedAt) VALUES
('El Profesor', 14, NOW(), NOW()),
('Tokio', 14, NOW(), NOW()),
('Berlín', 14, NOW(), NOW()),
('Nairobi', 14, NOW(), NOW()),
('Denver', 14, NOW(), NOW()),
('Río', 14, NOW(), NOW()),
('Helsinki', 14, NOW(), NOW()),
('Oslo', 14, NOW(), NOW()),
('Moscú', 14, NOW(), NOW()),
('Estocolmo (Mónica)', 14, NOW(), NOW()),
('Lisboa (Raquel)', 14, NOW(), NOW()),
('Palermo', 14, NOW(), NOW()),
('Bogotá', 14, NOW(), NOW()),
('Marsella', 14, NOW(), NOW()),
('Manila', 14, NOW(), NOW()),
('Alicia Sierra', 14, NOW(), NOW()),
('Arturo Román', 14, NOW(), NOW()),
('Ángel Rubio', 14, NOW(), NOW()),
('Coronel Tamayo', 14, NOW(), NOW()),
('Gandía', 14, NOW(), NOW());

-- Los Simpson (ID: 15)
INSERT INTO characters (name, categoryId, createdAt, updatedAt) VALUES
('Homer Simpson', 15, NOW(), NOW()),
('Marge Simpson', 15, NOW(), NOW()),
('Bart Simpson', 15, NOW(), NOW()),
('Lisa Simpson', 15, NOW(), NOW()),
('Maggie Simpson', 15, NOW(), NOW()),
('Abuelo Simpson', 15, NOW(), NOW()),
('Ned Flanders', 15, NOW(), NOW()),
('Mr. Burns', 15, NOW(), NOW()),
('Smithers', 15, NOW(), NOW()),
('Moe Szyslak', 15, NOW(), NOW()),
('Barney Gumble', 15, NOW(), NOW()),
('Krusty el Payaso', 15, NOW(), NOW()),
('Milhouse Van Houten', 15, NOW(), NOW()),
('Nelson Muntz', 15, NOW(), NOW()),
('Ralph Wiggum', 15, NOW(), NOW()),
('Jefe Wiggum', 15, NOW(), NOW()),
('Apu Nahasapeemapetilon', 15, NOW(), NOW()),
('Dr. Hibbert', 15, NOW(), NOW()),
('Dr. Nick', 15, NOW(), NOW()),
('Otto Mann', 15, NOW(), NOW()),
('Seymour Skinner', 15, NOW(), NOW()),
('Edna Krabappel', 15, NOW(), NOW()),
('Groundskeeper Willie', 15, NOW(), NOW()),
('Sideshow Bob', 15, NOW(), NOW()),
('Comic Book Guy', 15, NOW(), NOW()),
('Patty Bouvier', 15, NOW(), NOW()),
('Selma Bouvier', 15, NOW(), NOW()),
('Troy McClure', 15, NOW(), NOW()),
('Lionel Hutz', 15, NOW(), NOW()),
('Itchy y Scratchy', 15, NOW(), NOW());

-- Bob Esponja (ID: 16)
INSERT INTO characters (name, categoryId, createdAt, updatedAt) VALUES
('Bob Esponja', 16, NOW(), NOW()),
('Patricio Estrella', 16, NOW(), NOW()),
('Calamardo Tentáculos', 16, NOW(), NOW()),
('Don Cangrejo', 16, NOW(), NOW()),
('Arenita Mejillas', 16, NOW(), NOW()),
('Plankton', 16, NOW(), NOW()),
('Karen', 16, NOW(), NOW()),
('Gary', 16, NOW(), NOW()),
('Señora Puff', 16, NOW(), NOW()),
('Larry la Langosta', 16, NOW(), NOW()),
('Perla Cangrejo', 16, NOW(), NOW()),
('Sirena Man', 16, NOW(), NOW()),
('Chico Percebe', 16, NOW(), NOW()),
('El Holandés Volador', 16, NOW(), NOW()),
('Hombre Ray', 16, NOW(), NOW()),
('Dennis', 16, NOW(), NOW()),
('Rey Neptuno', 16, NOW(), NOW()),
('Triton', 16, NOW(), NOW());

-- Star Wars (ID: 17)
INSERT INTO characters (name, categoryId, createdAt, updatedAt) VALUES
('Luke Skywalker', 17, NOW(), NOW()),
('Darth Vader', 17, NOW(), NOW()),
('Princesa Leia', 17, NOW(), NOW()),
('Han Solo', 17, NOW(), NOW()),
('Chewbacca', 17, NOW(), NOW()),
('Obi-Wan Kenobi', 17, NOW(), NOW()),
('Yoda', 17, NOW(), NOW()),
('Emperador Palpatine', 17, NOW(), NOW()),
('R2-D2', 17, NOW(), NOW()),
('C-3PO', 17, NOW(), NOW()),
('Anakin Skywalker', 17, NOW(), NOW()),
('Padmé Amidala', 17, NOW(), NOW()),
('Mace Windu', 17, NOW(), NOW()),
('Qui-Gon Jinn', 17, NOW(), NOW()),
('Darth Maul', 17, NOW(), NOW()),
('Count Dooku', 17, NOW(), NOW()),
('General Grievous', 17, NOW(), NOW()),
('Kylo Ren', 17, NOW(), NOW()),
('Rey', 17, NOW(), NOW()),
('Finn', 17, NOW(), NOW()),
('Poe Dameron', 17, NOW(), NOW()),
('BB-8', 17, NOW(), NOW()),
('The Mandalorian', 17, NOW(), NOW()),
('Baby Yoda (Grogu)', 17, NOW(), NOW()),
('Boba Fett', 17, NOW(), NOW()),
('Jabba the Hutt', 17, NOW(), NOW()),
('Lando Calrissian', 17, NOW(), NOW()),
('Ahsoka Tano', 17, NOW(), NOW()),
('Captain Rex', 17, NOW(), NOW()),
('Grand Admiral Thrawn', 17, NOW(), NOW());

-- El Señor de los Anillos (ID: 18)
INSERT INTO characters (name, categoryId, createdAt, updatedAt) VALUES
('Frodo Bolsón', 18, NOW(), NOW()),
('Gandalf', 18, NOW(), NOW()),
('Aragorn', 18, NOW(), NOW()),
('Legolas', 18, NOW(), NOW()),
('Gimli', 18, NOW(), NOW()),
('Sam Gamyi', 18, NOW(), NOW()),
('Merry', 18, NOW(), NOW()),
('Pippin', 18, NOW(), NOW()),
('Boromir', 18, NOW(), NOW()),
('Gollum', 18, NOW(), NOW()),
('Sauron', 18, NOW(), NOW()),
('Saruman', 18, NOW(), NOW()),
('Bilbo Bolsón', 18, NOW(), NOW()),
('Elrond', 18, NOW(), NOW()),
('Galadriel', 18, NOW(), NOW()),
('Arwen', 18, NOW(), NOW()),
('Éowyn', 18, NOW(), NOW()),
('Éomer', 18, NOW(), NOW()),
('Théoden', 18, NOW(), NOW()),
('Faramir', 18, NOW(), NOW()),
('Treebeard', 18, NOW(), NOW()),
('Smaug', 18, NOW(), NOW()),
('Thorin Escudo de Roble', 18, NOW(), NOW()),
('Rey Brujo de Angmar', 18, NOW(), NOW());

-- Cantantes Pop (ID: 19)
INSERT INTO characters (name, categoryId, createdAt, updatedAt) VALUES
('Michael Jackson', 19, NOW(), NOW()),
('Madonna', 19, NOW(), NOW()),
('Beyoncé', 19, NOW(), NOW()),
('Taylor Swift', 19, NOW(), NOW()),
('Rihanna', 19, NOW(), NOW()),
('Lady Gaga', 19, NOW(), NOW()),
('Katy Perry', 19, NOW(), NOW()),
('Ariana Grande', 19, NOW(), NOW()),
('Justin Bieber', 19, NOW(), NOW()),
('Bruno Mars', 19, NOW(), NOW()),
('Ed Sheeran', 19, NOW(), NOW()),
('Adele', 19, NOW(), NOW()),
('Shakira', 19, NOW(), NOW()),
('Dua Lipa', 19, NOW(), NOW()),
('The Weeknd', 19, NOW(), NOW()),
('Harry Styles', 19, NOW(), NOW()),
('Billie Eilish', 19, NOW(), NOW()),
('Miley Cyrus', 19, NOW(), NOW()),
('Selena Gomez', 19, NOW(), NOW()),
('Demi Lovato', 19, NOW(), NOW()),
('Whitney Houston', 19, NOW(), NOW()),
('Mariah Carey', 19, NOW(), NOW()),
('Celine Dion', 19, NOW(), NOW()),
('BTS', 19, NOW(), NOW()),
('BLACKPINK', 19, NOW(), NOW()),
('One Direction', 19, NOW(), NOW()),
('Backstreet Boys', 19, NOW(), NOW()),
('NSYNC', 19, NOW(), NOW()),
('Spice Girls', 19, NOW(), NOW()),
('Britney Spears', 19, NOW(), NOW());

-- Cantantes Reggaeton (ID: 20)
INSERT INTO characters (name, categoryId, createdAt, updatedAt) VALUES
('Bad Bunny', 20, NOW(), NOW()),
('J Balvin', 20, NOW(), NOW()),
('Daddy Yankee', 20, NOW(), NOW()),
('Ozuna', 20, NOW(), NOW()),
('Maluma', 20, NOW(), NOW()),
('Anuel AA', 20, NOW(), NOW()),
('Karol G', 20, NOW(), NOW()),
('Nicky Jam', 20, NOW(), NOW()),
('Farruko', 20, NOW(), NOW()),
('Don Omar', 20, NOW(), NOW()),
('Wisin', 20, NOW(), NOW()),
('Yandel', 20, NOW(), NOW()),
('Arcángel', 20, NOW(), NOW()),
('De La Ghetto', 20, NOW(), NOW()),
('Rauw Alejandro', 20, NOW(), NOW()),
('Myke Towers', 20, NOW(), NOW()),
('Jhay Cortez', 20, NOW(), NOW()),
('Sech', 20, NOW(), NOW()),
('Feid', 20, NOW(), NOW()),
('Lunay', 20, NOW(), NOW()),
('Romeo Santos', 20, NOW(), NOW()),
('Prince Royce', 20, NOW(), NOW()),
('Becky G', 20, NOW(), NOW()),
('Rosalía', 20, NOW(), NOW());

-- Cantantes Rock (ID: 21)
INSERT INTO characters (name, categoryId, createdAt, updatedAt) VALUES
('Freddie Mercury', 21, NOW(), NOW()),
('Elvis Presley', 21, NOW(), NOW()),
('Mick Jagger', 21, NOW(), NOW()),
('John Lennon', 21, NOW(), NOW()),
('Paul McCartney', 21, NOW(), NOW()),
('David Bowie', 21, NOW(), NOW()),
('Prince', 21, NOW(), NOW()),
('Kurt Cobain', 21, NOW(), NOW()),
('Axl Rose', 21, NOW(), NOW()),
('Slash', 21, NOW(), NOW()),
('Ozzy Osbourne', 21, NOW(), NOW()),
('Robert Plant', 21, NOW(), NOW()),
('Jimmy Page', 21, NOW(), NOW()),
('Jimi Hendrix', 21, NOW(), NOW()),
('Eric Clapton', 21, NOW(), NOW()),
('Bruce Springsteen', 21, NOW(), NOW()),
('Bono', 21, NOW(), NOW()),
('Eddie Vedder', 21, NOW(), NOW()),
('Chester Bennington', 21, NOW(), NOW()),
('Dave Grohl', 21, NOW(), NOW()),
('Anthony Kiedis', 21, NOW(), NOW()),
('Chris Cornell', 21, NOW(), NOW()),
('Tom Morello', 21, NOW(), NOW()),
('Billie Joe Armstrong', 21, NOW(), NOW()),
('Eminem', 21, NOW(), NOW()),
('Kanye West', 21, NOW(), NOW()),
('Drake', 21, NOW(), NOW()),
('Snoop Dogg', 21, NOW(), NOW()),
('Jay-Z', 21, NOW(), NOW()),
('Tupac Shakur', 21, NOW(), NOW());

-- Futbolistas (ID: 22)
INSERT INTO characters (name, categoryId, createdAt, updatedAt) VALUES
('Lionel Messi', 22, NOW(), NOW()),
('Cristiano Ronaldo', 22, NOW(), NOW()),
('Neymar Jr.', 22, NOW(), NOW()),
('Kylian Mbappé', 22, NOW(), NOW()),
('Erling Haaland', 22, NOW(), NOW()),
('Robert Lewandowski', 22, NOW(), NOW()),
('Karim Benzema', 22, NOW(), NOW()),
('Luka Modrić', 22, NOW(), NOW()),
('Kevin De Bruyne', 22, NOW(), NOW()),
('Mohamed Salah', 22, NOW(), NOW()),
('Sadio Mané', 22, NOW(), NOW()),
('Virgil van Dijk', 22, NOW(), NOW()),
('Sergio Ramos', 22, NOW(), NOW()),
('Toni Kroos', 22, NOW(), NOW()),
('Zinedine Zidane', 22, NOW(), NOW()),
('Ronaldinho', 22, NOW(), NOW()),
('Ronaldo Nazário', 22, NOW(), NOW()),
('Diego Maradona', 22, NOW(), NOW()),
('Pelé', 22, NOW(), NOW()),
('Johan Cruyff', 22, NOW(), NOW()),
('Franz Beckenbauer', 22, NOW(), NOW()),
('Paolo Maldini', 22, NOW(), NOW()),
('Andrea Pirlo', 22, NOW(), NOW()),
('Xavi Hernández', 22, NOW(), NOW()),
('Andrés Iniesta', 22, NOW(), NOW()),
('David Beckham', 22, NOW(), NOW()),
('Thierry Henry', 22, NOW(), NOW()),
('Zlatan Ibrahimović', 22, NOW(), NOW()),
('Manuel Neuer', 22, NOW(), NOW()),
('Gianluigi Buffon', 22, NOW(), NOW());

-- NBA (ID: 23)
INSERT INTO characters (name, categoryId, createdAt, updatedAt) VALUES
('Michael Jordan', 23, NOW(), NOW()),
('LeBron James', 23, NOW(), NOW()),
('Kobe Bryant', 23, NOW(), NOW()),
('Stephen Curry', 23, NOW(), NOW()),
('Kevin Durant', 23, NOW(), NOW()),
('Shaquille ONeal', 23, NOW(), NOW()),
('Magic Johnson', 23, NOW(), NOW()),
('Larry Bird', 23, NOW(), NOW()),
('Tim Duncan', 23, NOW(), NOW()),
('Giannis Antetokounmpo', 23, NOW(), NOW()),
('Luka Dončić', 23, NOW(), NOW()),
('Ja Morant', 23, NOW(), NOW()),
('Joel Embiid', 23, NOW(), NOW()),
('Nikola Jokić', 23, NOW(), NOW()),
('Jayson Tatum', 23, NOW(), NOW()),
('Kawhi Leonard', 23, NOW(), NOW()),
('James Harden', 23, NOW(), NOW()),
('Russell Westbrook', 23, NOW(), NOW()),
('Damian Lillard', 23, NOW(), NOW()),
('Anthony Davis', 23, NOW(), NOW()),
('Kyrie Irving', 23, NOW(), NOW()),
('Chris Paul', 23, NOW(), NOW()),
('Dwyane Wade', 23, NOW(), NOW()),
('Dirk Nowitzki', 23, NOW(), NOW()),
('Allen Iverson', 23, NOW(), NOW()),
('Karl Malone', 23, NOW(), NOW()),
('John Stockton', 23, NOW(), NOW()),
('Hakeem Olajuwon', 23, NOW(), NOW()),
('Charles Barkley', 23, NOW(), NOW()),
('Dennis Rodman', 23, NOW(), NOW());

-- Videojuegos Nintendo (ID: 24)
INSERT INTO characters (name, categoryId, createdAt, updatedAt) VALUES
('Mario', 24, NOW(), NOW()),
('Luigi', 24, NOW(), NOW()),
('Princess Peach', 24, NOW(), NOW()),
('Bowser', 24, NOW(), NOW()),
('Yoshi', 24, NOW(), NOW()),
('Toad', 24, NOW(), NOW()),
('Donkey Kong', 24, NOW(), NOW()),
('Diddy Kong', 24, NOW(), NOW()),
('Link', 24, NOW(), NOW()),
('Zelda', 24, NOW(), NOW()),
('Ganondorf', 24, NOW(), NOW()),
('Samus Aran', 24, NOW(), NOW()),
('Kirby', 24, NOW(), NOW()),
('Meta Knight', 24, NOW(), NOW()),
('King Dedede', 24, NOW(), NOW()),
('Fox McCloud', 24, NOW(), NOW()),
('Falco Lombardi', 24, NOW(), NOW()),
('Captain Falcon', 24, NOW(), NOW()),
('Ness', 24, NOW(), NOW()),
('Lucas', 24, NOW(), NOW()),
('Pit', 24, NOW(), NOW()),
('Palutena', 24, NOW(), NOW()),
('Marth', 24, NOW(), NOW()),
('Roy', 24, NOW(), NOW()),
('Wario', 24, NOW(), NOW()),
('Waluigi', 24, NOW(), NOW()),
('Rosalina', 24, NOW(), NOW()),
('Isabelle', 24, NOW(), NOW()),
('Tom Nook', 24, NOW(), NOW()),
('Villager', 24, NOW(), NOW());

-- Videojuegos PlayStation (ID: 25)
INSERT INTO characters (name, categoryId, createdAt, updatedAt) VALUES
('Kratos', 25, NOW(), NOW()),
('Atreus', 25, NOW(), NOW()),
('Nathan Drake', 25, NOW(), NOW()),
('Ellie', 25, NOW(), NOW()),
('Joel', 25, NOW(), NOW()),
('Aloy', 25, NOW(), NOW()),
('Spider-Man (Miles Morales)', 25, NOW(), NOW()),
('Jin Sakai', 25, NOW(), NOW()),
('Ratchet', 25, NOW(), NOW()),
('Clank', 25, NOW(), NOW()),
('Sly Cooper', 25, NOW(), NOW()),
('Jak', 25, NOW(), NOW()),
('Daxter', 25, NOW(), NOW()),
('Cloud Strife', 25, NOW(), NOW()),
('Tifa Lockhart', 25, NOW(), NOW()),
('Aerith Gainsborough', 25, NOW(), NOW()),
('Sephiroth', 25, NOW(), NOW()),
('Crash Bandicoot', 25, NOW(), NOW()),
('Spyro', 25, NOW(), NOW()),
('Solid Snake', 25, NOW(), NOW()),
('Raiden', 25, NOW(), NOW()),
('Kazuya Mishima', 25, NOW(), NOW()),
('Heihachi Mishima', 25, NOW(), NOW()),
('Dante', 25, NOW(), NOW()),
('Nero', 25, NOW(), NOW()),
('Geralt de Rivia', 25, NOW(), NOW()),
('Ciri', 25, NOW(), NOW()),
('Leon S. Kennedy', 25, NOW(), NOW()),
('Claire Redfield', 25, NOW(), NOW()),
('Jill Valentine', 25, NOW(), NOW());

-- Pokémon (ID: 26)
INSERT INTO characters (name, categoryId, createdAt, updatedAt) VALUES
('Pikachu', 26, NOW(), NOW()),
('Charizard', 26, NOW(), NOW()),
('Mewtwo', 26, NOW(), NOW()),
('Eevee', 26, NOW(), NOW()),
('Gengar', 26, NOW(), NOW()),
('Snorlax', 26, NOW(), NOW()),
('Lucario', 26, NOW(), NOW()),
('Greninja', 26, NOW(), NOW()),
('Blaziken', 26, NOW(), NOW()),
('Garchomp', 26, NOW(), NOW()),
('Rayquaza', 26, NOW(), NOW()),
('Dragonite', 26, NOW(), NOW()),
('Gyarados', 26, NOW(), NOW()),
('Alakazam', 26, NOW(), NOW()),
('Machamp', 26, NOW(), NOW()),
('Blastoise', 26, NOW(), NOW()),
('Venusaur', 26, NOW(), NOW()),
('Jigglypuff', 26, NOW(), NOW()),
('Squirtle', 26, NOW(), NOW()),
('Bulbasaur', 26, NOW(), NOW()),
('Charmander', 26, NOW(), NOW()),
('Mew', 26, NOW(), NOW()),
('Arceus', 26, NOW(), NOW()),
('Ash Ketchum', 26, NOW(), NOW()),
('Misty', 26, NOW(), NOW()),
('Brock', 26, NOW(), NOW()),
('Team Rocket (Jessie y James)', 26, NOW(), NOW()),
('Professor Oak', 26, NOW(), NOW()),
('Gary Oak', 26, NOW(), NOW()),
('Cynthia', 26, NOW(), NOW());

-- Nickelodeon (ID: 27)
INSERT INTO characters (name, categoryId, createdAt, updatedAt) VALUES
('Tommy Pickles', 27, NOW(), NOW()),
('Chuckie Finster', 27, NOW(), NOW()),
('Angélica Pickles', 27, NOW(), NOW()),
('Arnold', 27, NOW(), NOW()),
('Helga Pataki', 27, NOW(), NOW()),
('CatDog', 27, NOW(), NOW()),
('Ren y Stimpy', 27, NOW(), NOW()),
('Jimmy Neutrón', 27, NOW(), NOW()),
('Timmy Turner', 27, NOW(), NOW()),
('Cosmo', 27, NOW(), NOW()),
('Wanda', 27, NOW(), NOW()),
('Danny Phantom', 27, NOW(), NOW()),
('El Tigre', 27, NOW(), NOW()),
('Aang', 27, NOW(), NOW()),
('Katara', 27, NOW(), NOW()),
('Sokka', 27, NOW(), NOW()),
('Zuko', 27, NOW(), NOW()),
('Toph', 27, NOW(), NOW()),
('Korra', 27, NOW(), NOW()),
('Invader Zim', 27, NOW(), NOW()),
('GIR', 27, NOW(), NOW()),
('Drake y Josh', 27, NOW(), NOW()),
('iCarly', 27, NOW(), NOW()),
('Victorious (Tori Vega)', 27, NOW(), NOW());

-- Cartoon Network (ID: 28)
INSERT INTO characters (name, categoryId, createdAt, updatedAt) VALUES
('Las Chicas Superpoderosas (Blossom)', 28, NOW(), NOW()),
('Las Chicas Superpoderosas (Bubbles)', 28, NOW(), NOW()),
('Las Chicas Superpoderosas (Buttercup)', 28, NOW(), NOW()),
('Mojo Jojo', 28, NOW(), NOW()),
('Dexter', 28, NOW(), NOW()),
('Dee Dee', 28, NOW(), NOW()),
('Johnny Bravo', 28, NOW(), NOW()),
('Vaca y Pollito', 28, NOW(), NOW()),
('Coraje el Perro Cobarde', 28, NOW(), NOW()),
('Ed, Edd y Eddy', 28, NOW(), NOW()),
('Billy y Mandy', 28, NOW(), NOW()),
('Puro Hueso', 28, NOW(), NOW()),
('Ben 10', 28, NOW(), NOW()),
('Gwen Tennyson', 28, NOW(), NOW()),
('Kevin Levin', 28, NOW(), NOW()),
('Finn el Humano', 28, NOW(), NOW()),
('Jake el Perro', 28, NOW(), NOW()),
('Marceline', 28, NOW(), NOW()),
('Princess Bubblegum', 28, NOW(), NOW()),
('Ice King', 28, NOW(), NOW()),
('Mordecai', 28, NOW(), NOW()),
('Rigby', 28, NOW(), NOW()),
('Gumball Watterson', 28, NOW(), NOW()),
('Darwin Watterson', 28, NOW(), NOW()),
('Steven Universe', 28, NOW(), NOW()),
('Garnet', 28, NOW(), NOW()),
('Pearl', 28, NOW(), NOW()),
('Amethyst', 28, NOW(), NOW()),
('Teen Titans (Robin)', 28, NOW(), NOW()),
('Teen Titans (Starfire)', 28, NOW(), NOW());

-- Shrek y DreamWorks (ID: 29)
INSERT INTO characters (name, categoryId, createdAt, updatedAt) VALUES
('Shrek', 29, NOW(), NOW()),
('Fiona', 29, NOW(), NOW()),
('Burro', 29, NOW(), NOW()),
('Gato con Botas', 29, NOW(), NOW()),
('Lord Farquaad', 29, NOW(), NOW()),
('Príncipe Encantador', 29, NOW(), NOW()),
('Hada Madrina', 29, NOW(), NOW()),
('Pinocho', 29, NOW(), NOW()),
('Los Tres Cerditos', 29, NOW(), NOW()),
('Po (Kung Fu Panda)', 29, NOW(), NOW()),
('Tigresa', 29, NOW(), NOW()),
('Master Shifu', 29, NOW(), NOW()),
('Tai Lung', 29, NOW(), NOW()),
('Alex (Madagascar)', 29, NOW(), NOW()),
('Marty (Madagascar)', 29, NOW(), NOW()),
('Gloria (Madagascar)', 29, NOW(), NOW()),
('Melman', 29, NOW(), NOW()),
('Los Pingüinos', 29, NOW(), NOW()),
('Rey Julien', 29, NOW(), NOW()),
('Hiccup', 29, NOW(), NOW()),
('Toothless', 29, NOW(), NOW()),
('Astrid', 29, NOW(), NOW()),
('Metro Man', 29, NOW(), NOW()),
('Megamind', 29, NOW(), NOW()),
('Spirit', 29, NOW(), NOW()),
('Turbo', 29, NOW(), NOW()),
('The Boss Baby', 29, NOW(), NOW()),
('Mr. Peabody', 29, NOW(), NOW());

-- Películas de Terror (ID: 30)
INSERT INTO characters (name, categoryId, createdAt, updatedAt) VALUES
('Freddy Krueger', 30, NOW(), NOW()),
('Jason Voorhees', 30, NOW(), NOW()),
('Michael Myers', 30, NOW(), NOW()),
('Ghostface', 30, NOW(), NOW()),
('Chucky', 30, NOW(), NOW()),
('Pennywise', 30, NOW(), NOW()),
('Jigsaw', 30, NOW(), NOW()),
('Leatherface', 30, NOW(), NOW()),
('Hannibal Lecter', 30, NOW(), NOW()),
('Norman Bates', 30, NOW(), NOW()),
('Jack Torrance', 30, NOW(), NOW()),
('Regan MacNeil (El Exorcista)', 30, NOW(), NOW()),
('Samara (The Ring)', 30, NOW(), NOW()),
('Kayako (The Grudge)', 30, NOW(), NOW()),
('Annabelle', 30, NOW(), NOW()),
('Valak (La Monja)', 30, NOW(), NOW()),
('Art the Clown', 30, NOW(), NOW()),
('Pinhead', 30, NOW(), NOW()),
('Candyman', 30, NOW(), NOW()),
('Xenomorph (Alien)', 30, NOW(), NOW()),
('Predator', 30, NOW(), NOW()),
('Dracula', 30, NOW(), NOW()),
('Frankenstein', 30, NOW(), NOW()),
('La Momia', 30, NOW(), NOW()),
('El Hombre Lobo', 30, NOW(), NOW());

-- Películas de Acción (ID: 31)
INSERT INTO characters (name, categoryId, createdAt, updatedAt) VALUES
('John Wick', 31, NOW(), NOW()),
('James Bond', 31, NOW(), NOW()),
('Ethan Hunt', 31, NOW(), NOW()),
('Jason Bourne', 31, NOW(), NOW()),
('John McClane', 31, NOW(), NOW()),
('Terminator', 31, NOW(), NOW()),
('RoboCop', 31, NOW(), NOW()),
('Rambo', 31, NOW(), NOW()),
('Rocky Balboa', 31, NOW(), NOW()),
('Indiana Jones', 31, NOW(), NOW()),
('Mad Max', 31, NOW(), NOW()),
('Neo', 31, NOW(), NOW()),
('Trinity', 31, NOW(), NOW()),
('Morpheus', 31, NOW(), NOW()),
('John Connor', 31, NOW(), NOW()),
('Sarah Connor', 31, NOW(), NOW()),
('Ellen Ripley', 31, NOW(), NOW()),
('Dominic Toretto', 31, NOW(), NOW()),
('Brian OConner', 31, NOW(), NOW()),
('Hobbs', 31, NOW(), NOW()),
('Jack Reacher', 31, NOW(), NOW()),
('Bryan Mills (Taken)', 31, NOW(), NOW()),
('The Bride (Kill Bill)', 31, NOW(), NOW()),
('John Rambo', 31, NOW(), NOW()),
('Martin Riggs', 31, NOW(), NOW());

-- Comedia Romántica (ID: 32)
INSERT INTO characters (name, categoryId, createdAt, updatedAt) VALUES
('Bridget Jones', 32, NOW(), NOW()),
('Mr. Darcy', 32, NOW(), NOW()),
('Elle Woods', 32, NOW(), NOW()),
('Noah (The Notebook)', 32, NOW(), NOW()),
('Allie (The Notebook)', 32, NOW(), NOW()),
('Julia Roberts (Pretty Woman)', 32, NOW(), NOW()),
('Edward Lewis (Pretty Woman)', 32, NOW(), NOW()),
('Harry Burns (When Harry Met Sally)', 32, NOW(), NOW()),
('Sally Albright', 32, NOW(), NOW()),
('William Thacker (Notting Hill)', 32, NOW(), NOW()),
('Anna Scott (Notting Hill)', 32, NOW(), NOW()),
('Tom Hansen (500 Days of Summer)', 32, NOW(), NOW()),
('Summer Finn', 32, NOW(), NOW()),
('Patrick Verona (10 Things I Hate)', 32, NOW(), NOW()),
('Kat Stratford', 32, NOW(), NOW()),
('Joseph (Crazy Rich Asians)', 32, NOW(), NOW()),
('Rachel Chu', 32, NOW(), NOW()),
('Lara Jean', 32, NOW(), NOW()),
('Peter Kavinsky', 32, NOW(), NOW()),
('Mia Thermopolis', 32, NOW(), NOW());

-- Youtubers (ID: 33)
INSERT INTO characters (name, categoryId, createdAt, updatedAt) VALUES
('PewDiePie', 33, NOW(), NOW()),
('MrBeast', 33, NOW(), NOW()),
('Rubius', 33, NOW(), NOW()),
('AuronPlay', 33, NOW(), NOW()),
('Ibai Llanos', 33, NOW(), NOW()),
('Fernanfloo', 33, NOW(), NOW()),
('JuegaGerman', 33, NOW(), NOW()),
('Luisito Comunica', 33, NOW(), NOW()),
('Markiplier', 33, NOW(), NOW()),
('Jacksepticeye', 33, NOW(), NOW()),
('Ninja', 33, NOW(), NOW()),
('xQc', 33, NOW(), NOW()),
('Pokimane', 33, NOW(), NOW()),
('Mizkif', 33, NOW(), NOW()),
('Ludwig', 33, NOW(), NOW()),
('Vegetta777', 33, NOW(), NOW()),
('TheWillyrex', 33, NOW(), NOW()),
('DjMariio', 33, NOW(), NOW()),
('TheGrefg', 33, NOW(), NOW()),
('KSI', 33, NOW(), NOW()),
('Logan Paul', 33, NOW(), NOW()),
('Jake Paul', 33, NOW(), NOW()),
('David Dobrik', 33, NOW(), NOW()),
('Emma Chamberlain', 33, NOW(), NOW());

-- Personajes Históricos (ID: 34)
INSERT INTO characters (name, categoryId, createdAt, updatedAt) VALUES
('Napoleón Bonaparte', 34, NOW(), NOW()),
('Cleopatra', 34, NOW(), NOW()),
('Julio César', 34, NOW(), NOW()),
('Alejandro Magno', 34, NOW(), NOW()),
('Leonardo da Vinci', 34, NOW(), NOW()),
('Albert Einstein', 34, NOW(), NOW()),
('Isaac Newton', 34, NOW(), NOW()),
('Galileo Galilei', 34, NOW(), NOW()),
('Cristóbal Colón', 34, NOW(), NOW()),
('Juana de Arco', 34, NOW(), NOW()),
('Genghis Khan', 34, NOW(), NOW()),
('Marco Polo', 34, NOW(), NOW()),
('William Shakespeare', 34, NOW(), NOW()),
('Mozart', 34, NOW(), NOW()),
('Beethoven', 34, NOW(), NOW()),
('Pablo Picasso', 34, NOW(), NOW()),
('Abraham Lincoln', 34, NOW(), NOW()),
('Martin Luther King', 34, NOW(), NOW()),
('Mahatma Gandhi', 34, NOW(), NOW()),
('Nelson Mandela', 34, NOW(), NOW()),
('Marie Curie', 34, NOW(), NOW()),
('Charles Darwin', 34, NOW(), NOW()),
('Nikola Tesla', 34, NOW(), NOW()),
('Simón Bolívar', 34, NOW(), NOW()),
('Winston Churchill', 34, NOW(), NOW()),
('George Washington', 34, NOW(), NOW()),
('Thomas Edison', 34, NOW(), NOW()),
('Benjamin Franklin', 34, NOW(), NOW()),
('Confucio', 34, NOW(), NOW()),
('Buda', 34, NOW(), NOW());

-- Mitología Griega (ID: 35)
INSERT INTO characters (name, categoryId, createdAt, updatedAt) VALUES
('Zeus', 35, NOW(), NOW()),
('Poseidón', 35, NOW(), NOW()),
('Hades', 35, NOW(), NOW()),
('Atenea', 35, NOW(), NOW()),
('Apolo', 35, NOW(), NOW()),
('Artemisa', 35, NOW(), NOW()),
('Afrodita', 35, NOW(), NOW()),
('Ares', 35, NOW(), NOW()),
('Hermes', 35, NOW(), NOW()),
('Hefesto', 35, NOW(), NOW()),
('Dioniso', 35, NOW(), NOW()),
('Hera', 35, NOW(), NOW()),
('Deméter', 35, NOW(), NOW()),
('Perséfone', 35, NOW(), NOW()),
('Hércules', 35, NOW(), NOW()),
('Aquiles', 35, NOW(), NOW()),
('Odiseo (Ulises)', 35, NOW(), NOW()),
('Perseo', 35, NOW(), NOW()),
('Teseo', 35, NOW(), NOW()),
('Jasón', 35, NOW(), NOW()),
('Helena de Troya', 35, NOW(), NOW()),
('Medusa', 35, NOW(), NOW()),
('Minotauro', 35, NOW(), NOW()),
('Cíclope', 35, NOW(), NOW()),
('Centauro', 35, NOW(), NOW()),
('Pegaso', 35, NOW(), NOW()),
('Prometeo', 35, NOW(), NOW()),
('Atlas', 35, NOW(), NOW()),
('Cronos', 35, NOW(), NOW()),
('Titanes', 35, NOW(), NOW());

-- =============================================
-- FIN DEL SEED
-- =============================================

SELECT 
    c.name as categoria,
    COUNT(ch.id) as total_personajes
FROM categories c
LEFT JOIN characters ch ON c.id = ch.categoryId
GROUP BY c.id, c.name
ORDER BY c.name;
